version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://shyamkrishnasby:Shyam123456@cluster0.zynk5xc.mongodb.net/anscer?retryWrites=true&w=majority
      - SESSION_SECRET=abcdeA121212
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
